import type { Company, PermissionMatrix, User } from "../shared/data/types";

// Espelho dos dados de exemplo do backend (backend/scripts/database/seed.py),
// usado pela API em memória dos testes. Todos os registros são fictícios.
export const INITIAL_COMPANIES: Company[] = [
    {
        id: "1",
        name: "Aurora Tecnologia",
        cnpj: "00.000.000/0001-01",
        sector: "Tecnologia",
        city: "São Paulo / SP",
        status: "active",
        email: "contato@aurora.exemplo",
        phone: "(11) 0000-0001",
        createdAt: "2026-01-12",
    },
    {
        id: "2",
        name: "Verde Campo",
        cnpj: "00.000.000/0002-02",
        sector: "Agronegócio",
        city: "Goiânia / GO",
        status: "active",
        email: "contato@verdecampo.exemplo",
        phone: "(62) 0000-0002",
        createdAt: "2026-02-03",
    },
    {
        id: "3",
        name: "Norte Logística",
        cnpj: "00.000.000/0003-03",
        sector: "Logística",
        city: "Manaus / AM",
        status: "pending",
        email: "contato@nortelogistica.exemplo",
        phone: "(92) 0000-0003",
        createdAt: "2026-03-18",
    },
    {
        id: "4",
        name: "Studio Forma",
        cnpj: "00.000.000/0004-04",
        sector: "Design",
        city: "Curitiba / PR",
        status: "active",
        email: "contato@studioforma.exemplo",
        createdAt: "2026-05-07",
    },
    {
        id: "5",
        name: "Costa & Mar",
        cnpj: "00.000.000/0005-05",
        sector: "Turismo",
        city: "Florianópolis / SC",
        status: "inactive",
        email: "contato@costaemar.exemplo",
        phone: "(48) 0000-0005",
        createdAt: "2026-06-22",
    },
    {
        id: "6",
        name: "Ponto Saúde",
        cnpj: "00.000.000/0006-06",
        sector: "Saúde",
        city: "Recife / PE",
        status: "active",
        email: "contato@pontosaude.exemplo",
        phone: "(81) 0000-0006",
        createdAt: "2026-08-30",
    },
];

export const INITIAL_USERS: User[] = [
    {
        id: "1",
        name: "Mariana Alves",
        email: "mariana.alves@aurora.exemplo",
        companyId: "1",
        role: "admin",
        status: "active",
        lastAccess: "2026-09-25T12:42:00+00:00",
    },
    {
        id: "2",
        name: "Rafael Lima",
        email: "rafael.lima@verdecampo.exemplo",
        companyId: "2",
        role: "editor",
        status: "active",
        lastAccess: "2026-09-24T20:15:00+00:00",
    },
    {
        id: "3",
        name: "Beatriz Souza",
        email: "beatriz.souza@nortelogistica.exemplo",
        companyId: "3",
        role: "viewer",
        status: "pending",
        lastAccess: null,
    },
    {
        id: "4",
        name: "Carlos Mendes",
        email: "carlos.mendes@studioforma.exemplo",
        companyId: "4",
        role: "editor",
        status: "active",
        lastAccess: "2026-09-22T17:03:00+00:00",
    },
    {
        id: "5",
        name: "Fernanda Rocha",
        email: "fernanda.rocha@costaemar.exemplo",
        companyId: "5",
        role: "viewer",
        status: "inactive",
        lastAccess: "2026-08-10T14:20:00+00:00",
    },
    {
        id: "6",
        name: "Lucas Pereira",
        email: "lucas.pereira@pontosaude.exemplo",
        companyId: "6",
        role: "admin",
        status: "active",
        lastAccess: "2026-09-25T11:10:00+00:00",
    },
];

export const INITIAL_PERMISSIONS: PermissionMatrix = {
    "companies.view": { admin: true, editor: true, viewer: true },
    "companies.create": { admin: true, editor: true, viewer: false },
    "companies.edit": { admin: true, editor: true, viewer: false },
    "companies.delete": { admin: true, editor: false, viewer: false },
    "users.view": { admin: true, editor: true, viewer: true },
    "users.manage": { admin: true, editor: false, viewer: false },
    "permissions.manage": { admin: true, editor: false, viewer: false },
};
